### PR TITLE
Updated Podfile to reflect new target name: "Payments Demo" to "Mobil…

### PR DESCRIPTION
**Pull request by mattkenney**
…e Pay" and update pod framework link phase to match new target name.

### CODE REVIEW

**Comment by svenresch** [comment]
Hey there Matt. Happy to see you found this project and are interested in it!!

Just wondering if you can explain this pull request a little more as I'm not sure as to why you want this change made. Can you please clarify?

Thx much, Sven

**Comment by mattkenney** [comment]
Hi Sven,

If you do this:
```
git clone https://github.com/Beanstream/mobilepayments-demo.git
cd mobilepayments-demo/client/ios/
pod install
```
you get this:
```
Analyzing dependencies
[!] Unable to find a target named `Payments Demo`, did find `Mobile Pay`.
```
and "pod install" fails, so the project cannot be built - you get a "Shell Script Invocation Error" because no "Podfile.lock" file yet exists.

It looks like the name of the target in this Xcode project has been changed from "Payments Demo" to "Mobile Pay". I edited the Podfile to match that change so "pod install" generates a CocoaPod framework for the "Mobile Pay" target.

With that change to the Podfile, "pod install" generates "Pods_Mobile_Pay.framework" and adds it to the list of frameworks in the "Link Binary With Libraries" section of the "Build Phases" tab of the target configuration. However, it does not remove the previously added "Pods_Payments_Demo.framework", so you get a "Apple Mach-O Linker Error" because that framework does not exist.

I removed that "Pods_Payments_Demo.framework" entry, so the project can be built and run.

Another way to make this project build successfully would be to just change the target name back from "Mobile Pay" to "Payments Demo", but I think it is a better practice to not have the target name be the same as the project name - it is less confusing when they are distinct.

**Comment by mattkenney** [comment]
PS: according to the [guidelines](https://guides.cocoapods.org/using/using-cocoapods.html), "Podfile.lock" should be kept under version control.

**Comment by svenresch** [comment]
Thanks again Matt for all your comments and contributions!! I have cloned a clean directory structure and confirmed the issue you reported.

We prefer to stick with the 'Payments Demo' name and so I have instead renamed the target and any other files/resources to match. Running `pod install` seems to work fine now. I have also committed the podfile.lock to git.

Hope this project is of benefit to you and looking forward to working with you some more! Cheers and Merry Christmas.

:-) Sven

**Pull request closed without merging**
